account-url: "http://account.default.svc.cluster.local:8080"
treatment-url: "http://treatment.default.svc.cluster.local:8080"
payment-url: "http://payment.default.svc.cluster.local:8080"

management:
  endpoint:
    health:
      probes:
        enabled: true