apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    version: v1
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        version: v1
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 2
          failureThreshold: 5
        readinessProbe: 
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m