apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    service: {{ .Values.appname }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    name: web
    appProtocol: http
  selector:
    app: {{ .Values.appname }}